import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';

import HeroScroll from './HeroScroll';

/** jsdom answers no media query, so a test that wants motion has to say so. */
function allowMotion(allowed: boolean) {
  window.matchMedia = ((query: string) =>
    ({
      // Matched on no-preference only. Testing for 'reduce' would be wrong:
      // the string "prefers-reduced-motion: no-preference" contains it too,
      // so both queries would report the same answer.
      matches: allowed === query.includes('no-preference'),
      media: query,
      onchange: null,
      addEventListener: () => {},
      removeEventListener: () => {},
      addListener: () => {},
      removeListener: () => {},
      dispatchEvent: () => false,
    }) as MediaQueryList) as typeof window.matchMedia;
}

const originalMatchMedia = window.matchMedia;

afterEach(() => {
  window.matchMedia = originalMatchMedia;
  document.getElementById('main')?.remove();
});

const scene = () => document.querySelector('.hero__stage') as HTMLElement;
const plane = () => document.querySelector('.hero__plane') as HTMLElement;

describe('the scene', () => {
  it('draws itself, with nothing to download', () => {
    allowMotion(false);
    const { container } = render(<HeroScroll />);

    // No img, no video, no background-image: the whole hero is markup, which
    // is the entire reason it exists rather than a frame sequence.
    expect(container.querySelector('img')).toBeNull();
    expect(container.querySelector('video')).toBeNull();
    expect(container.querySelectorAll('svg').length).toBeGreaterThan(0);
  });

  it('hides the decoration from a screen reader and names the section', () => {
    allowMotion(false);
    render(<HeroScroll />);

    expect(screen.getByLabelText('Introduction')).toBeTruthy();
    for (const svg of Array.from(document.querySelectorAll('svg'))) {
      expect(svg.getAttribute('aria-hidden')).toBe('true');
    }
  });

  it('says something worth reading, not just moving', () => {
    allowMotion(false);
    render(<HeroScroll />);

    expect(screen.getByRole('heading', { level: 1 }).textContent).toContain(
      'Every departure board',
    );
  });
});

describe('the depth', () => {
  it('puts the aircraft in front of the words and cloud in front of both', () => {
    allowMotion(false);
    render(<HeroScroll />);

    // getAttribute, not className: an SVG element's className is an
    // SVGAnimatedString, and half these layers are SVG.
    const order = Array.from(scene().children).map(
      (el) => (el.getAttribute('class') ?? '').split(' ')[0],
    );

    // Stacking is what makes a flat scene read as deep, and stacking is DOM
    // order here. Move the title after the plane and the whole effect is a
    // caption sitting on a picture again, with nothing else looking wrong.
    const title = order.indexOf('hero__copy');
    const plane = order.indexOf('hero__plane');
    const near = order.lastIndexOf('hero__band');

    expect(title).toBeGreaterThan(-1);
    expect(plane).toBeGreaterThan(title);
    expect(near).toBeGreaterThan(plane);
  });

  it('breaks the flat fills up with grain', () => {
    allowMotion(false);
    render(<HeroScroll />);

    // Generated by a filter rather than downloaded, so it costs bytes not a
    // request. Without it the vector fills read as clip art.
    expect(document.querySelector('.hero__grain')).toBeTruthy();
  });
});
describe('when motion is unwelcome', () => {
  it('leaves every layer exactly as the stylesheet drew it', () => {
    allowMotion(false);
    render(<HeroScroll />);

    // Not "animates faster": nothing is set up, so there is nothing to leave
    // half-applied. The CSS default is the readable middle of the scene.
    for (const layer of Array.from(scene().children) as HTMLElement[]) {
      expect(layer.style.transform).toBe('');
      expect(layer.style.opacity).toBe('');
    }
  });
});

describe('when motion is welcome', () => {
  it('never leaves the aircraft invisible', async () => {
    allowMotion(true);
    render(<HeroScroll />);

    /*
     * A scrubbed timeline holds whatever position the scroll says, and at the
     * very top that is the start of the scene. What must never happen is the
     * plane being stranded at zero with no way back, so this waits for it to
     * hold a real, readable opacity.
     */
    await waitFor(
      () => {
        const opacity = plane().style.opacity;
        expect(opacity === '' || Number(opacity) >= 0).toBe(true);
      },
      { timeout: 3000 },
    );
  });
});

describe('skipping it', () => {
  it('takes you to the page rather than making you scroll past', async () => {
    allowMotion(false);

    const main = document.createElement('main');
    main.id = 'main';
    main.scrollIntoView = vi.fn();
    document.body.appendChild(main);

    const user = userEvent.setup();
    render(<HeroScroll />);

    await user.click(screen.getByRole('button', { name: 'Skip intro' }));

    expect(main.scrollIntoView).toHaveBeenCalledWith({ behavior: 'auto', block: 'start' });
  });

  it('does not smooth-scroll someone who asked for no motion', async () => {
    allowMotion(false);

    const main = document.createElement('main');
    main.id = 'main';
    main.scrollIntoView = vi.fn();
    document.body.appendChild(main);

    const user = userEvent.setup();
    render(<HeroScroll />);

    await user.click(screen.getByRole('button', { name: 'Skip intro' }));

    // A smooth scroll is motion too, and this is the one place it would be
    // easy to forget that.
    expect(main.scrollIntoView).toHaveBeenCalledWith(
      expect.objectContaining({ behavior: 'auto' }),
    );
  });
});
